
int tmin();
int test_tmin();
int bitOr(int, int);
int test_bitOr(int, int);
int addOK(int, int);
int test_addOK(int, int);
int conditional(int, int, int);
int test_conditional(int, int, int);
int anyEvenBit();
int test_anyEvenBit();
int allOddBits();
int test_allOddBits();
int sign(int);
int test_sign(int);
int isLessOrEqual(int, int);
int test_isLessOrEqual(int, int);
int bang(int);
int test_bang(int);
int rotateLeft(int, int);
int test_rotateLeft(int, int);
int fitsBits(int, int);
int test_fitsBits(int, int);
int tc2sm(int);
int test_tc2sm(int);
int byteSwap(int, int, int);
int test_byteSwap(int, int, int);
int leastBitPos(int);
int test_leastBitPos(int);
